In [13]:
import numpy as np
t1 = np.zeros((2,2,2))
t2 = np.ones((2,2,2))
t3 = np.concatenate((t1,t2),axis=1)

t3

array([[[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]]])

In [14]:
t4 = np.concatenate((t1,t2),axis=2)
t4

array([[[0., 0., 1., 1.],
        [0., 0., 1., 1.]],

       [[0., 0., 1., 1.],
        [0., 0., 1., 1.]]])

In [15]:
t5 = np.concatenate((t1,t2),axis=0)
t5

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
t6 = np.arange(1,9).reshape((2,4))
print(t6)
t6.transpose()

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])